project_name: golastic
builds:
  - env: [ CGO_ENABLED=0 ]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

nightly:
  publish_release: true
  keep_single_release: true
  name_template: '{{ incminor .Version }}-nightly'
  tag_name: nightly